### ISSUE TITLE
Button mapping detection and input sending mismatch

### ISSUE THREAD

**Issue by Xyzzizzle** [Iquis/rev2-wakeup-tool#29]
Hey man,

The SendInput method you're using to trigger the Recording Playback in Gear is using the "physical" keyboard buttons, whereas the game is operating on a higher layer where the physical keycaps have been mapped according to the users's keyboard layout.

Meaning if you have users using a non-standard keyboard layout (Colemak, Dvorak, whatever), where these two don't happen to align, the playback key will not actually be hit

**Comment by Iquis** [comment]
Ok. I'll check if it would be possible to send a controller input to trigger the replay

**Comment by SamD64** [comment]
As a related note here, on keyboard I play with the "P" button as my RC macro, and I have to rebind it in order to practice things on kbd. 
If you stick with the previous method of sending a keypress to trigger the replay, consider sending an input like F24 or something else that keyboards likely don't have physically, but there is built in support from windows for. It would prevent needing to rebind my keys to use the utility.
