### ISSUE TITLE
Dummy can do impossible blitz inputs

### ISSUE THREAD

**Issue by ask09ok** [Iquis/rev2-wakeup-tool#75]
`6PH`, `6KH`, and `6SH` are supposed to give a throw if the opponent is in throw range, otherwise perform the character's 6P/6K/6S. This is how you input throw OSes.

Using `!6PH`, the dummy does throw if in range, blitz if not. This isn't supposed to be possible; blitz can only be activated from `5`,`2`, and `3`. Even playing the recording manually, or using it as an input after the ! frame results in this. For example, `!6,5,6*20,6PH` gives a dash for 20 frames and then a blitz.

Incidentally, this also means it's impossible to train against throw OSes, because there's no way to make the dummy do them. Even something like `6P,6PH` kara cancels the 6P input into a blitz on frame 2. 

Addendum: The dummy can also do blitzes while holding the `8` and `9` directions, which again should be impossible. `7`, `4`, and `1` give FD as expected.

Addendum 2: Holding a direction and pressing `P`/`K`/`S` and then `H` on consecutive frames results in a blitz even though the two buttons are never held together. This lets you blitz even from a `4` direction (something like `4H, 4PH`). `7` and `1` still give FD.

Addendum 3: `5P,5H` gives a blitz despite P and H never being pressed on the same frame. This is true for all directions where blitz is valid (including `6P,6H` and `4P,4H` which normally shouldn't work even when pressed together).

Addendum 4: With Baiken, the dummy can do azami using `9SH`, `8SH`, and `3SH`, which Baiken can't normally do. However, it still can't produce azami with `6SH`. This gives a 6SH throw OS, which is the expected result.

**Comment by worsety** [comment]
This is normal behaviour as far as I can see.  The game does not require the buttons to be pressed on the same frame, just no more than 2f apart.  If both were pressed at most 2f before wakeup and no direction is held on the first frame the dummy can act, it will blitz.  `!6,5,6*20,6PH` (or `6PH*2`) will blitz kara cancel 6P into standing blitz because there are two attack buttons buffered and no direction held after the replay finishes.
Proximity OS throw/blitz is also possible manually, it's just difficult.  In any case, the reversal tool doesn't cheat, it just inputs more precisely than a human, in this case by not continuing to hold directions after the last input.
